CREATE TABLE capxportfolio (
    id INT AUTO_INCREMENT PRIMARY KEY,
    noOfShares INT NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    website VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
